changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Features / 新功能
      labels:
        - enhancement
        - feature
    - title: Fixes / 修正
      labels:
        - bug
        - fix
    - title: Maintenance / 維護
      labels:
        - dependencies
        - documentation
        - ci
    - title: Other changes / 其他變更
      labels:
        - "*"
